# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box_check_update = false
  config.vm.synced_folder '.', '/vagrant' , disabled: true

  config.vm.define 'ansible-vm' do |cfg|
    cfg.vm.box = 'centos/7'
    # cfg.vm.box = 'bento/centos-7.2'
    cfg.vm.hostname = 'ansible-vm'
    cfg.vm.network 'private_network', ip: '192.168.33.10'
    cfg.vm.provider 'virtualbox' do |v|
      v.name = 'ansible-vm'
      v.memory = 1024
    end
    cfg.vm.provision 'ansible' do |ansible|
      # Comment the following line if you are not using a RHEL distribution
      ansible.galaxy_role_file = 'requirements.yml'
      ansible.playbook = 'site.yml'
      ansible.inventory_path = 'inventory'
      ansible.limit = 'ansible-vm'
      ansible.verbose = 'v'
    end
  end

end
